backend:
  name: github
  repo: alijaya/gridsome-alijaya

site_url: https://alijaya.id

media_folder: "static/uploads"
public_folder: "/uploads"

publish_mode: editorial_workflow

collections:
  - label: "BlogPost"
    name: "blog_post"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Cover Image", name: "cover_image", required: false, widget: "image"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Tags", name: "tags", required: false, widget: "list"}
      - {label: "Content", name: "content", widget: "markdown"}
  - label: "Static"
    name: "static"
    folder: "content/static"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Content", name: "content", widget: "markdown"}